FROM ubuntu:latest
MAINTAINER RoundRobin "kahina.ferroukhi@gmail.com"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
RUN pip install --upgrade pip
RUN pip install Flask
RUN pip install py2neo
